apiVersion: apps/v1
kind: Deployment
metadata:
  name: Formulamonks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Formulamonks
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: Formulamonks
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: Formulamonks
        image: testharshaacr.azurecr.io/Formulamonks:tag
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: Formulamonks
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Formulamonks